feat: add job trigger and get log ouput
jenkins-zh/jenkins-cli pull request #771
Opened 2024-07-05 05:59 UTC by feiguoL

**Make sure that you've checked the boxes below before you submit PR:**

### Always
- [x] Resolves jenkins-zh/jenkins-cli#595
- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Written well with PR title, we generate the [release notes](https://github.com/jenkins-zh/jenkins-cli/releases) base on that

### For the bug fixes or features only

- [ ] [Quality Gate Passed](https://sonarcloud.io/dashboard?id=jenkins-zh_jenkins-cli). Change this URL to your PR.
- [ ] The coverage is xxx on the new lines
- [ x] I've tested it by manual in the following platform
  - [x] MacOS
  - [x] Linux
  - [x] Windows
- [ ] Unit Test covered
- [ ] e2e Test covered

![image](https://github.com/jenkins-zh/jenkins-cli/assets/45145345/d7afd19b-67b1-4d0a-bbe4-5bb0a1e9a1ac)
![image](https://github.com/jenkins-zh/jenkins-cli/assets/45145345/6a434570-00c1-457b-a67d-44f72fa6294a)

2024-07-05 06:08 UTC, LinuxSuRen requested changes
Thanks for your effort. But please make sure you set the correct email address using the following commands:

```shell
git config --local user.email your-github-email@xxx.com
```

![image](https://github.com/jenkins-zh/jenkins-cli/assets/1450685/defa62d7-a248-45cd-896c-6c6a6622fc9f)

2024-07-05 08:28 UTC, feiguoL commented
> Thanks for your effort. But please make sure you set the correct email address using the following commands:
> 
> ```shell
> git config --local user.email your-github-email@xxx.com
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/1450685/346021939-defa62d7-a248-45cd-896c-6c6a6622fc9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjgzNzAsIm5iZiI6MTcyMDE2ODA3MCwicGF0aCI6Ii8xNDUwNjg1LzM0NjAyMTkzOS1kZWZhNjJkNy1hMjQ4LTQ1Y2QtODk2Yy02YzZhNjYyMmZjOWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDVUMDgyNzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzdiYjVhMDk1ZDc1NDVmZDQ5Y2E0NTQ2NGJjYzVjNWUzYzQ1YzAxZTA5ZGMwYjJjZTdjODc1ZThiOWU5YTgwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GJBkcdYpfb7NgeJfeosr2BstDQAW5UwoBha7NSKiwtY)

Fix email error done！
![image](https://github.com/jenkins-zh/jenkins-cli/assets/45145345/6a367c8d-e7c1-4b8a-91d9-aaec714beeb6)

2024-08-05 02:08 UTC, LinuxSuRen commented
hi @feiguoL please update your branch from the master branch. I made some changes #773

2024-08-13 02:38 UTC, feiguoL commented
> hi @feiguoL please update your branch from the master branch. I made some changes #773

update done

2024-12-23 09:20 UTC, LinuxSuRen commented on Dockerfile
> +ENTRYPOINT ["jclih"]
This will be break-change. Other users will get errors.

2024-12-23 09:20 UTC, LinuxSuRen commented on .jenkins-cli.yaml
What's the purpose of this file?

2024-12-23 09:22 UTC, LinuxSuRen commented
hi @feiguoL , it works well when I test it on my computer. But I still find two potential minor issues. Please take a look at it. Thanks for your time again.

2025-01-15 08:48 UTC, feiguoL commented on .jenkins-cli.yaml
bin binary

2025-01-16 09:17 UTC, feiguoL commented on Makefile
> +pre-build:
add fmt vet

2025-01-16 09:29 UTC, LinuxSuRen approved these changes

2025-01-16 09:33 UTC, merged